version: '2'
services:
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
            - my_application_img1
            - my_application_img2
            - my_application_img3
    ports:
            - '80:80'
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
  my_application_img1:
    image: flask-index
    depends_on:
            - redis-server
            - proxy-server
  my_application_img2:
    image: flask-index
    depends_on:
            - redis-server
            - proxy-server
  my_application_img3:
    image: flask-index
    depends_on:
            - redis-server
            - proxy-server
  redis-server:
    image: redis-server
    container_name: alex_redis-server_1
    ports:
            - "6379"
  proxy-server:
    image: proxy
    container_name: proxy
    ports:
            - "8080"
                                      
